Update for frontier backup proxies

diff --git a/bin/updateGenerators b/bin/updateGenerators
--- a/bin/updateGenerators
+++ b/bin/updateGenerators
@@ -8,6 +8,7 @@
 
 DEST="/cvmfs/atlas.cern.ch/repo/sw/Generators"
 PDFDIR="lhapdfsets/current"
+MADGRAPHMODELSDIR="madgraph/models"
 if [ -s "$INSTCONF" ] ; then
     DEST="`grep -i ^GeneratorsPath= $INSTCONF | cut -d= -f 2`"
     CHANGELOG="`grep -i ^ChangeLog= $INSTCONF | cut -d= -f 2`"
@@ -90,6 +91,91 @@ EOD
         fi
     fi
 done
+
+# MadGraphModels
+#[ ! -d $DEST/$MADGRAPHMODELSDIR ] && mkdir -p $DEST/$MADGRAPHMODELSDIR/latest
+#[ ! -f $DEST/$MADGRAPHMODELSDIR/.cvmfscatalog ] && touch $DEST/$MADGRAPHMODELSDIR/.cvmfscatalog
+#timeout 60s svn ls svn+ssh://$SVNUSERNAME@svn.cern.ch/reps/atlasoff/Generators/MadGraphModels/tags > $TMPTAGS
+#if [ $? -eq 0 ] ; then
+#    latesttag="`cat $TMPTAGS | tail -n 1`"
+#else
+#    unset latesttag
+#fi
+#rm -f $TMPTAGS
+#if [ -n "$latesttag" ] ; then
+#    if [ ! -f $DEST/$MADGRAPHMODELSDIR/tag ] ; then
+#        echo "Checking out MadGraphModels $latesttag into $DEST/$MADGRAPHMODELSDIR/latest"
+#        svn co svn+ssh://$SVNUSERNAME@svn.cern.ch/reps/atlasoff/Generators/MadGraphModels/tags/$latesttag $DEST/$MADGRAPHMODELSDIR/latest
+#        currrc=$?
+#        if [ $currrc -eq 0 ] ; then
+#            echo $latesttag > $DEST/$MADGRAPHMODELSDIR/tag
+#            echo "	* + MadGraphModels $latesttag" > ${TRANSACTION}.latest
+#            cat ${TRANSACTION}.latest >> $TRANSACTION
+#            let rc=$rc+$currrc
+#        fi
+#    else
+#        if [ "`cat $DEST/$MADGRAPHMODELSDIR/tag`" != "$latesttag" ] ; then
+#            cd $DEST/$MADGRAPHMODELSDIR/latest
+#            echo "Updating MadGraphModels from `cat $DEST/$MADGRAPHMODELSDIR/tag` to $latesttag in $DEST/$MADGRAPHMODELSDIR/latest"
+#            svn switch svn+ssh://$SVNUSERNAME@svn.cern.ch/reps/atlasoff/Generators/MadGraphModels/tags/$latesttag
+#            currrc=$?
+#            if [ $currrc -eq 0 ] ; then
+#                echo $latesttag > $DEST/$MADGRAPHMODELSDIR/tag
+#                echo "	* + MadGraphModels $latesttag" > ${TRANSACTION}.latest
+#                cat ${TRANSACTION}.latest >> $TRANSACTION
+#                let rc=$rc+$currrc
+#            fi
+#        fi
+#    fi
+#    BADDIRS="`\ls -d $DEST/$MADGRAPHMODELSDIR/latest/*-??-??-?? 2>/dev/null | wc -l`"
+#    if [ $BADDIRS -gt 0 ] ; then
+#        eval $CVMFSABORT
+#        if [ -n "$MAILTO" ] ; then
+#            mail -s "[ATLAS CVMFS ERROR] `hostname`" "$MAILTO" <<EOD
+#Dear admin,
+#the following releases failed to install in CVMFS @ `hostname` due to a bad checkout
+#
+#`cat ${TRANSACTION}.latest`
+#
+#Regards,
+#
+#     Your faithful installation agent
+#EOD
+#        fi
+#        rm -f ${TRANSACTION}*
+#        # Clear the install lock
+#        $HOME/bin/unlock-install
+#        exit 100
+#    fi
+#fi
+
+currrc=0
+kinit -kt ${SVNUSERNAME}.keytab ${SVNUSERNAME}@CERN.CH
+MGSRC="https://:@gitlab.cern.ch:8443/atlas-generators-team/MadGraphModels.git"
+MGDST="$DEST/$MADGRAPHMODELSDIR/latest"
+echo "Syncing MadGraphModels from $MGSRC to $MGDST"
+if [ ! -d `dirname $MGDST` ] ; then
+    mkdir -p `dirname $MGDST`
+    git clone $MGSRC $MGDST
+    currrc=$?
+    [ $currrc -eq 0 ] && touch ${MGDST}/.cvmfscatalog
+else
+    cd $MGDST
+    git fetch
+    HEADREV=$(git rev-parse HEAD)
+    LOCALREV=$(git rev-parse @{u})
+    if [ $HEADREV != $LOCALREV ]; then
+        git pull
+        currrc=$?
+    else
+        currrc=10
+    fi
+fi
+if [ $currrc -eq 0 ] ; then
+    TSTAMP="`date +%Y%m%d%H%M`"
+    echo "	* + MadGraphModels $TSTAMP" >> $TRANSACTION
+fi
+let rc=$rc+$currrc
 
 # PDFSets
 # For this to work, since the synchronization is performed without afs tokens,
diff --git a/bin/updateSimulationData b/bin/updateSimulationData
--- a/bin/updateSimulationData
+++ b/bin/updateSimulationData
@@ -1,15 +1,13 @@
-#!/bin/sh
+#!/bin/bash
 
 [ -z "$1" ] && USERNAME="atlcvmfs"
 
 # Configuration scripts
 [ -f "$PWD/.arelinstrc" ] && INSTCONF="$PWD/.arelinstrc"
 [ -f "$HOME/.arelinstrc" ] && INSTCONF="$HOME/.arelinstrc"
-GDEXCLLIST="$HOME/.groupdata.exclude"
-[ ! -f "$GDEXCLLIST" ] && touch $GDEXCLLIST
 
 if [ -s "$INSTCONF" ] ; then
-    GDPATHS="`grep -i ^GroupDataPath= $INSTCONF | cut -d= -f 2`"
+    SDPATHS="`grep -i ^SimulationDataPath= $INSTCONF | cut -d= -f 2`"
     CHANGELOG="`grep -i ^ChangeLog= $INSTCONF | cut -d= -f 2`"
     USERNAME="`grep -i ^UserName= $INSTCONF | cut -d= -f 2`"
     SVNUSERNAME="`grep -i ^SvnUserName= $INSTCONF | cut -d= -f 2`"
@@ -21,47 +19,43 @@ fi
 
 TRANSACTION=/tmp/tmp.transaction.$$
 CURRDIR="$PWD"
-[ -z "$MAXFILES" ] && MAXFILES=500
-
+MAXFILES=500
+UPSTREAM='@{u}'
 rm -f ${TRANSACTION}*
 rc=0
 echo "Preparing transfer"
 kinit -kt ${SVNUSERNAME}.keytab ${SVNUSERNAME}@CERN.CH
-[ -z "$GDPATHS" ] && GDPATHS="/afs/cern.ch/atlas/www/GROUPS/DATABASE/GroupData/:/cvmfs/atlas.cern.ch/repo/sw/database/GroupData"
-GDPINDX=0
-for GDPATH in `echo $GDPATHS | sed 's/,/ /g'`; do
-  GDSRC="lxplus.cern.ch:`echo $GDPATH | cut -d: -f 1`"
-  GDDST="`echo $GDPATH | cut -d: -f 2`"
-  let GDPINDX=$GDPINDX+1
-  echo "Syncing GroupData [$GDPINDX] from $GDSRC to $GDDST"
-  rsync -nirl -e "ssh -l ${SVNUSERNAME} -i $HOME/.ssh/${SVNUSERNAME}_id_dsa -o GSSAPIDelegateCredentials=yes -o GSSAPIAuthentication=yes" $GDSRC $GDDST | \
-     egrep -v '^sending|^sent|^total|^cannot|^could not|^$' | egrep '^>|^c' | awk '{print $2}' | head -n $MAXFILES | grep -v -f ${GDEXCLLIST} | tee ${TRANSACTION}.flist
-  [ -n "$DEBUG" ] && cat ${TRANSACTION}.flist
-  if [ `cat ${TRANSACTION}.flist | wc -l` -gt 0 ] ; then
-      # Wait for the main lock
-      if [ ! -f $TRANSACTION ] ; then
-          $HOME/bin/lock-install updateGroupData
+[ -z "$SDPATHS" ] && SDPATHS="/atlas-simulation-team/Geant4SetupConfigReference.git:/cvmfs/atlas.cern.ch/repo/sw/Simulation/Geant4SetupConfigReference"
+SDPINDX=0
+$HOME/bin/lock-install updateSimulationData
+rc=$?
+eval $CVMFSTRANSACTION
+[ $rc -ne 0 ] && exit $rc
+for SDPATH in `echo $SDPATHS | sed 's/,/ /g'`; do
+  SDSRC="https://:@gitlab.cern.ch:8443`echo $SDPATH | cut -d: -f 1`"
+  SDDST="`echo $SDPATH | cut -d: -f 2`"
+  let SDPINDX=$SDPINDX+1
+  echo "Syncing SimulationData [$SDPINDX] from $SDSRC to $SDDST"
+  if [ ! -d `dirname $SDDST` ] ; then
+      mkdir -p `dirname $SDDST`
+      git clone $SDSRC $SDDST
+      rc=$?
+      [ $rc -eq 0 ] && touch ${SDDST}/.cvmfscatalog
+  else
+      cd $SDDST
+      git fetch
+      HEADREV=$(git rev-parse HEAD)
+      LOCALREV=$(git rev-parse @{u})
+      if [ $HEADREV != $LOCALREV ]; then
+          git pull
           rc=$?
       else
-          rc=0
+          rc=10
       fi
-      if [ $rc -ne 0 ]; then
-          exit $rc
-      fi
-      [ ! -f $TRANSACTION ] && eval $CVMFSTRANSACTION
-      echo "Synchronizing `cat ${TRANSACTION}.flist | wc -l` files"
-      rsync -dlptgov --delete --files-from=${TRANSACTION}.flist -e "ssh -l ${SVNUSERNAME} -i $HOME/.ssh/${SVNUSERNAME}_id_dsa -o GSSAPIDelegateCredentials=yes -o GSSAPIAuthentication=yes" $GDSRC $GDDST 2> ${TRANSACTION}.err
-      rc=$?
-      if [ $rc -eq 0 -a -s "${TRANSACTION}.flist" ] ; then
-          TSTAMP="`date +%Y%m%d%H%M`"
-          echo "	* + GroupData $GDSRC $TSTAMP" >> $TRANSACTION
-      else
-          cat ${TRANSACTION}.flist
-          cat ${TRANSACTION}.err
-      fi
-  else
-      echo "No files to synchronize from $GDSRC to $GDDST"
-      rm -f ${TRANSACTION}.flist
+  fi
+  if [ $rc -eq 0 ] ; then
+      TSTAMP="`date +%Y%m%d%H%M`"
+      echo "	* + SimulationData $SDSRC $TSTAMP" >> $TRANSACTION
   fi
 done
 
@@ -112,8 +106,8 @@ if [ -n "$CHANGELOG" -a -s "$TRANSACTION" ] ; then
 fi
 
 # Publish changes
-if [ $rc -eq 0 ] ; then
-    if [ -n "$CVMFSPUBLISH" -a -s $TRANSACTION ] ; then
+if [ -s $TRANSACTION ] ; then
+    if [ -n "$CVMFSPUBLISH" ] ; then
         $CVMFSPUBLISH
         if [ -n "$MAILTO" ] ; then
             echo "Sending notification"
@@ -123,8 +117,6 @@ the following releases have been installed in CVMFS @ `hostname`
 
 `cat $TRANSACTION`
 
-Number of files transferred: `cat ${TRANSACTION}.flist | wc -l`
-
 Regards,
 
      Your faithful installation agent
@@ -133,24 +125,12 @@ EOD
     fi
 else
     [ -n "$CVMFSABORT" ] && $CVMFSABORT
-    if [ -n "$MAILTO" ] ; then
-        echo "Sending notification"
-        mail -s "[ATLAS CVMFS ERROR] `hostname`" "$MAILTO" <<EOD
-Dear admin,
-the GroupData failed to install in CVMFS.
-Regards,
-
-     Your faithful installation agent
-EOD
-    fi
 fi
 
-if [ -s $TRANSACTION ] ; then
-    # Clear the install lock
-    $HOME/bin/unlock-install
+# Clear the install lock
+$HOME/bin/unlock-install
 
-    # Cleanup
-    rm -f ${TRANSACTION}*
-fi
+# Cleanup
+rm -f ${TRANSACTION}*
 
 exit $rc
