New functionalities

diff --git a/bin/updateAGISData b/bin/updateAGISData
--- a/bin/updateAGISData
+++ b/bin/updateAGISData
@@ -1,5 +1,48 @@
 #!/bin/sh
 
+get_etag() {
+    TARGET=$1
+    [ -s $ETAGCONF ] && ETAG="`grep -i ^${TARGET} ${ETAGCONF} 2> /dev/null | sed 's/\r//g' | awk '{print $2}'`" || unset ETAG
+    echo $ETAG
+}
+
+download() {
+    TARGET="$1"
+    SRCURL="$2"
+    echo -n "Downloading $TARGET: "
+    ETAGOLD="`get_etag $TARGET`"
+    ETAGNEW="`install $TARGET "$SRCURL"`"
+    rc=$?
+    if [ "$ETAGOLD" != "$ETAGNEW" ] ; then
+        UPDATED="yes"
+        echo "$TARGET: $ETAGNEW" >> ${ETAGCONF}.tmp
+        echo "new tag $ETAGNEW"
+    else
+        echo "$TARGET: $ETAGOLD" >> ${ETAGCONF}.tmp
+        echo "tag unchanged"
+    fi
+    return $rc
+}
+
+install() {
+    TARGET="$1"
+    SRCURL="$2"
+    ETAG="`get_etag $TARGET`"
+    [ -n "$ETAG" ] && ETAG_OPT="--header 'If-None-Match: $ETAG'" || unset ETAG_OPT
+    eval curl -sw "%{http_code}" --connect-timeout 60 -o "${DEST}/${TARGET}" --dump-header $TMPHEADER $ETAG_OPT '$SRCURL' > $TMPRC
+    HTTPRC="`cat $TMPRC`" && rm -f $TMPRC
+    [ -z "$HTTPRC" ] && HTTPRC=404
+    if [ $HTTPRC -eq 200 -o $HTTPRC -eq 304 ] ; then
+        rc=0
+        [ $HTTPRC -eq 200 ] && ETAG="`grep -i ^etag $TMPHEADER 2>/dev/null | awk '{print $2}'`"
+    else
+        rc=1
+    fi
+    echo "$ETAG"
+    rm -f $TMPHEADER
+    return $rc
+}
+
 # Configuration scripts
 [ -f "$PWD/.arelinstrc" ] && INSTCONF="$PWD/.arelinstrc"
 [ -f "$HOME/.arelinstrc" ] && INSTCONF="$HOME/.arelinstrc"
@@ -10,32 +53,68 @@ if [ -s "$INSTCONF" ] ; then
     CHANGELOG="`grep -i ^ChangeLog= $INSTCONF | cut -d= -f 2`"
     USERNAME="`grep -i ^UserName= $INSTCONF | cut -d= -f 2`"
     AGISURL="`grep -i ^AGISDataURL= $INSTCONF | cut -d= -f 2`"
+    TOAURL="`grep -i ^AGISToAURL= $INSTCONF | cut -d= -f 2`"
     SCHEDCONFURL="`grep -i ^AGISSchedconfURL= $INSTCONF | cut -d= -f 2-`"
+    DDMEP="`grep -i ^AGISDDMendpointURL= $INSTCONF | cut -d= -f 2-`"
+    DDMOS="`grep -i ^AGISDDMobjectstoresURL= $INSTCONF | cut -d= -f 2-`"
+    OSSVC="`grep -i ^AGISOSServicesURL= $INSTCONF | cut -d= -f 2-`"
+    CVMFSTRANSACTION="`grep -i ^cvmfs_transaction= $INSTCONF | cut -d= -f 2`"
     CVMFSPUBLISH="`grep -i ^cvmfs_publish= $INSTCONF | cut -d= -f 2`"
+    CVMFSABORT="`grep -i ^cvmfs_abort= $INSTCONF | cut -d= -f 2`"
     MAILTO="`grep -i ^MailTo= $INSTCONF | cut -d= -f 2`"
 fi
 
 TRANSACTION=/tmp/tmp.transaction.$$
 CURRDIR="$PWD"
-MAINLOCK=$HOME/.install.lock
-MAINLOCKOPTS="-60 -r 180"
+ETAGCONF="$HOME/.agisetags"
+TMPHEADER="/tmp/etags.$$"
+TMPRC="/tmp/updateagisrc.$$"
+TMPDATA="/tmp/updateagisdata.$$"
+UPDATED="no"
+
+# Cleanup the temp etags conf file
+rm -f ${ETAGCONF}.tmp
 
 # Wait for the main lock
-echo "Setting or waiting for lock to clear"
-eval lockfile $MAINLOCKOPTS $MAINLOCK
+$HOME/bin/lock-install updateAGISData
 rc=$?
 if [ $rc -ne 0 ]; then
   exit $rc
 fi
 
-rm -f $TRANSACTION
+$CVMFSTRANSACTION
+rm -f $TRANSACTION $TMPHEADER
 rc=0
 [ ! -d $DEST ] && mkdir -p $DEST
-curl -S --connect-timeout 60 -o "$DEST/agis_site_info.json" "$AGISURL"
-currrc=$?
-curl -S --connect-timeout 60 -o "$DEST/agis_schedconf.json" "$SCHEDCONFURL"
+
+# agis_site_info
+download agis_site_info.json "$AGISURL"
 let currrc=$currrc+$?
-if [ $currrc -eq 0 ] ; then
+
+# agis_schedconf
+download agis_schedconf.json "$SCHEDCONFURL"
+let currrc=$currrc+$?
+
+# ToACache
+download ToACache.py "$TOAURL"
+let currrc=$currrc+$?
+
+# DDMendpoints
+download agis_ddmendpoints.json "$DDMEP"
+let currrc=$currrc+$?
+
+# DDMendpointsObjectstores
+download agis_ddmendpoints_objectstores.json "$DDMOS"
+let currrc=$currrc+$?
+
+# OSServices
+download agis_os_services.json "$OSSVC"
+let currrc=$currrc+$?
+
+# Replace the etags file
+mv -f ${ETAGCONF}.tmp ${ETAGCONF}
+
+if [ $currrc -eq 0 -a "$UPDATED" = "yes" ] ; then
     echo "	* + AGISData `date +%Y%m%d%H%M%S`" >> $TRANSACTION
     let rc=$rc+$currrc
 fi
@@ -101,10 +180,21 @@ Regards,
      Your faithful installation agent
 EOD
         fi
+    else
+        [ -n "$CVMFSABORT" ] && $CVMFSABORT
     fi
     # Clear the install lock
-    echo "Clearing the install lock"
-    rm -f $MAINLOCK
+    $HOME/bin/unlock-install
+else
+    if [ -n "$MAILTO" ] ; then
+        mail -s "[ATLAS CVMFS ERROR] `hostname`" "$MAILTO" <<EOD
+Dear admin,
+an updateAGISData job failed to run on `hostname`
+Regards,
+    
+     Your faithful installation agent
+EOD
+    fi
 fi
 
 # Cleanup
diff --git a/bin/updateGroupData b/bin/updateGroupData
--- a/bin/updateGroupData
+++ b/bin/updateGroupData
@@ -6,55 +6,49 @@
 [ -f "$PWD/.arelinstrc" ] && INSTCONF="$PWD/.arelinstrc"
 [ -f "$HOME/.arelinstrc" ] && INSTCONF="$HOME/.arelinstrc"
 
-DEST="/cvmfs/atlas.cern.ch/repo/sw/PandaPilot"
+DEST="/cvmfs/atlas.cern.ch/repo/sw/Generators"
 if [ -s "$INSTCONF" ] ; then
-    DEST="`grep -i ^PandaPilotPath= $INSTCONF | cut -d= -f 2`"
+    DEST="`grep -i ^GroupDataPath= $INSTCONF | cut -d= -f 2`"
     CHANGELOG="`grep -i ^ChangeLog= $INSTCONF | cut -d= -f 2`"
     USERNAME="`grep -i ^UserName= $INSTCONF | cut -d= -f 2`"
     SVNUSERNAME="`grep -i ^SvnUserName= $INSTCONF | cut -d= -f 2`"
-    PILOTPKG="`grep -i ^PandaPilotPackage= $INSTCONF | cut -d= -f 2`"
     CVMFSTRANSACTION="`grep -i ^cvmfs_transaction= $INSTCONF | cut -d= -f 2`"
     CVMFSABORT="`grep -i ^cvmfs_abort= $INSTCONF | cut -d= -f 2`"
     CVMFSPUBLISH="`grep -i ^cvmfs_publish= $INSTCONF | cut -d= -f 2`"
+    MAILTO="`grep -i ^MailTo= $INSTCONF | cut -d= -f 2`"
 fi
 
 TRANSACTION=/tmp/tmp.transaction.$$
 CURRDIR="$PWD"
+MAXFILES=200
 
-# Wait for the main lock
-$HOME/bin/lock-install updatePilot
-rc=$?
-if [ $rc -ne 0 ]; then
-  exit $rc
-fi
-
-$CVMFSTRANSACTION
-rm -f $TRANSACTION
+rm -f ${TRANSACTION}*
 rc=0
-[ ! -d $DEST/$PILOTPKG ] && mkdir -p $DEST/$PILOTPKG/latest
-[ ! -f $DEST/$PILOTPKG/.cvmfscatalog ] && touch $DEST/$PILOTPKG/.cvmfscatalog
-if [ ! -f $DEST/$PILOTPKG/latest/PILOTVERSION ] ; then
-    echo "Checking out the latest PandaPilot into $DEST/$PILOTPKG/latest"
-    git clone https://github.com/PanDAWMS/$PILOTPKG $DEST/$PILOTPKG/latest
-    currrc=$?
-    if [ $currrc -eq 0 ] ; then
-        cp -f $DEST/$PILOTPKG/latest/PILOTVERSION $DEST/$PILOTPKG/tag
-        echo "	* + PandaPilot `cat $DEST/$PILOTPKG/latest/PILOTVERSION`" >> $TRANSACTION
-        let rc=$rc+$currrc
+GDSRC="lxplus.cern.ch:/afs/cern.ch/atlas/www/GROUPS/DATABASE/GroupData/"
+echo "Syncing GroupData from $GDSRC to $DEST"
+rsync -nirl -e "ssh -l ${SVNUSERNAME} -i $HOME/.ssh/${SVNUSERNAME}_id_dsa" $GDSRC $DEST | egrep -v '^sending|^sent|^total|^$' | egrep '^>|^c' | awk '{print $2}' | head -n $MAXFILES | tee ${TRANSACTION}.flist
+if [ `cat ${TRANSACTION}.flist | wc -l` -gt 0 ] ; then
+    # Wait for the main lock
+    $HOME/bin/lock-install updateGroupData
+    rc=$?
+    if [ $rc -ne 0 ]; then
+        exit $rc
+    fi
+    eval $CVMFSTRANSACTION
+    echo "Synchronizing `cat ${TRANSACTION}.flist | wc -l` files"
+    rsync -dlptgov --delete --files-from=${TRANSACTION}.flist -e "ssh -l ${SVNUSERNAME} -i $HOME/.ssh/${SVNUSERNAME}_id_dsa" $GDSRC $DEST 2> ${TRANSACTION}.err
+    rc=$?
+    if [ $rc -eq 0 -a -s "${TRANSACTION}.flist" ] ; then
+        TSTAMP="`date +%Y%m%d%H%M`"
+        echo "	* + GroupData $TSTAMP" >> $TRANSACTION
+    else
+        cat ${TRANSACTION}.err
     fi
 else
-    cd $DEST/$PILOTPKG/latest
-    echo "Updating PandaPilot in $DEST/$PILOTPKG/latest"
-    git pull
-    currrc=$?
-    if [ $currrc -eq 0 ] ; then
-        if [ "`cat $DEST/$PILOTPKG/latest/PILOTVERSION`" != "`cat $DEST/$PILOTPKG/tag`" ] ; then
-            cp -f $DEST/$PILOTPKG/latest/PILOTVERSION $DEST/$PILOTPKG/tag
-            echo "	* + PandaPilot `cat $DEST/$PILOTPKG/latest/PILOTVERSION`" >> $TRANSACTION
-            let rc=$rc+$currrc
-        fi
-    fi
+    echo "No files to synchronize"
+    rm -f ${TRANSACTION}.flist
 fi
+
 cd $CURRDIR
 
 # Automatic Changelog
@@ -105,14 +99,42 @@ fi
 if [ $rc -eq 0 ] ; then
     if [ -n "$CVMFSPUBLISH" -a -s $TRANSACTION ] ; then
         $CVMFSPUBLISH
-    else
-        [ -n "$CVMFSABORT" ] && $CVMFSABORT
+        if [ -n "$MAILTO" ] ; then
+            echo "Sending notification"
+            mail -s "[ATLAS CVMFS UPDATE] `hostname`" "$MAILTO" <<EOD
+Dear admin,
+the following releases have been installed in CVMFS @ `hostname`
+
+`cat $TRANSACTION`
+
+Number of files transferred: `cat ${TRANSACTION}.flist | wc -l`
+
+Regards,
+
+     Your faithful installation agent
+EOD
+        fi
     fi
-    # Clear the install lock
-    $HOME/bin/unlock-install
+else
+    [ -n "$CVMFSABORT" ] && $CVMFSABORT
+    if [ -n "$MAILTO" ] ; then
+        echo "Sending notification"
+        mail -s "[ATLAS CVMFS ERROR] `hostname`" "$MAILTO" <<EOD
+Dear admin,
+the GroupData failed to install in CVMFS.
+Regards,
+
+     Your faithful installation agent
+EOD
+    fi
 fi
 
-# Cleanup
-rm -f $TRANSACTION
+if [ -s $TRANSACTION ] ; then
+    # Clear the install lock
+    $HOME/bin/unlock-install
+
+    # Cleanup
+    rm -f ${TRANSACTION}*
+fi
 
 exit $rc
